// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pluxy3dBE.Repository.Data;

#nullable disable

namespace Pluxy3dBE.Repository.Data.Migrations
{
    [DbContext(typeof(AppDbContextFromDb))]
    partial class AppDbContextFromDbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Pluxy3dBE.Entities.Carrito", b =>
                {
                    b.Property<int>("CarritoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("carrito_id");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_actualizacion");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("TEXT")
                        .HasColumnName("usuario_id");

                    b.HasKey("CarritoId")
                        .HasName("PK__carritos__8647FB0916512604");

                    b.HasIndex("UsuarioId");

                    b.ToTable("carritos", (string)null);
                });

            modelBuilder.Entity("Pluxy3dBE.Entities.CarritoItem", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("item_id");

                    b.Property<int?>("Cantidad")
                        .HasColumnType("INTEGER")
                        .HasColumnName("cantidad");

                    b.Property<int?>("CarritoId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("carrito_id");

                    b.Property<int?>("ImpresoraId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("impresora_id");

                    b.HasKey("ItemId")
                        .HasName("PK__carrito___52020FDD15942EA5");

                    b.HasIndex("CarritoId");

                    b.HasIndex("ImpresoraId");

                    b.ToTable("carrito_items", (string)null);
                });

            modelBuilder.Entity("Pluxy3dBE.Entities.CategoriasProducto", b =>
                {
                    b.Property<int>("CategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("categoria_id");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("nombre");

                    b.HasKey("CategoriaId")
                        .HasName("PK__categori__DB875A4FF877F55C");

                    b.ToTable("categorias_productos", (string)null);
                });

            modelBuilder.Entity("Pluxy3dBE.Entities.ComponentesPersonalizable", b =>
                {
                    b.Property<int>("ComponenteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("componente_id");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("nombre");

                    b.Property<string>("Tipo")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("tipo");

                    b.HasKey("ComponenteId")
                        .HasName("PK__componen__7480EE8F96F73AEE");

                    b.ToTable("componentes_personalizables", (string)null);
                });

            modelBuilder.Entity("Pluxy3dBE.Entities.ConsultasContacto", b =>
                {
                    b.Property<int>("ConsultaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("consulta_id");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<DateTime?>("Fecha")
                        .HasColumnType("datetime")
                        .HasColumnName("fecha");

                    b.Property<string>("Mensaje")
                        .HasColumnType("text")
                        .HasColumnName("mensaje");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("nombre");

                    b.HasKey("ConsultaId")
                        .HasName("PK__consulta__BBB59BD855340A4D");

                    b.ToTable("consultas_contacto", (string)null);
                });

            modelBuilder.Entity("Pluxy3dBE.Entities.DetalleVentum", b =>
                {
                    b.Property<int>("DetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("detalle_id");

                    b.Property<int?>("Cantidad")
                        .HasColumnType("INTEGER")
                        .HasColumnName("cantidad");

                    b.Property<int?>("ImpresoraId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("impresora_id");

                    b.Property<decimal?>("PrecioUnitario")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("precio_unitario");

                    b.Property<int?>("VentaId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("venta_id");

                    b.HasKey("DetalleId")
                        .HasName("PK__detalle___91B12E7087ED20B4");

                    b.HasIndex("ImpresoraId");

                    b.HasIndex("VentaId");

                    b.ToTable("detalle_venta", (string)null);
                });

            modelBuilder.Entity("Pluxy3dBE.Entities.DireccionesUsuario", b =>
                {
                    b.Property<int>("DireccionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("direccion_id");

                    b.Property<string>("Calle")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("calle");

                    b.Property<string>("Ciudad")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("ciudad");

                    b.Property<string>("CodigoPostal")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("codigo_postal");

                    b.Property<bool?>("EsPrincipal")
                        .HasColumnType("INTEGER")
                        .HasColumnName("es_principal");

                    b.Property<string>("Provincia")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("provincia");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("TEXT")
                        .HasColumnName("usuario_id");

                    b.HasKey("DireccionId")
                        .HasName("PK__direccio__3CE1758CA4ADA568");

                    b.HasIndex("UsuarioId");

                    b.ToTable("direcciones_usuarios", (string)null);
                });

            modelBuilder.Entity("Pluxy3dBE.Entities.EstadosVentum", b =>
                {
                    b.Property<int>("EstadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("estado_id");

                    b.Property<string>("Nombre")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("nombre");

                    b.HasKey("EstadoId")
                        .HasName("PK__estados___053774EF0D8DF71A");

                    b.ToTable("estados_venta", (string)null);
                });

            modelBuilder.Entity("Pluxy3dBE.Entities.FavoritosUsuario", b =>
                {
                    b.Property<int>("FavoritoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("favorito_id");

                    b.Property<int?>("ProductoId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("producto_id");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("TEXT")
                        .HasColumnName("usuario_id");

                    b.HasKey("FavoritoId")
                        .HasName("PK__favorito__B8BA20CA91C0EAE8");

                    b.HasIndex("ProductoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("favoritos_usuarios", (string)null);
                });

            modelBuilder.Entity("Pluxy3dBE.Entities.HistorialNavegacion", b =>
                {
                    b.Property<int>("HistorialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("historial_id");

                    b.Property<DateTime?>("Fecha")
                        .HasColumnType("datetime")
                        .HasColumnName("fecha");

                    b.Property<string>("Pagina")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("pagina");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("TEXT")
                        .HasColumnName("usuario_id");

                    b.HasKey("HistorialId")
                        .HasName("PK__historia__68FE18EE9C5C8CFA");

                    b.HasIndex("UsuarioId");

                    b.ToTable("historial_navegacion", (string)null);
                });

            modelBuilder.Entity("Pluxy3dBE.Entities.ImpresorasPersonalizada", b =>
                {
                    b.Property<int>("ImpresoraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("impresora_id");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_creacion");

                    b.Property<string>("NombrePersonalizado")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("nombre_personalizado");

                    b.Property<int?>("ProductoId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("producto_id");

                    b.Property<decimal?>("TotalFinal")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("total_final");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("TEXT")
                        .HasColumnName("usuario_id");

                    b.HasKey("ImpresoraId")
                        .HasName("PK__impresor__2BDA8F2755B6A4E9");

                    b.HasIndex("ProductoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("impresoras_personalizadas", (string)null);
                });

            modelBuilder.Entity("Pluxy3dBE.Entities.LogsIum", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("log_id");

                    b.Property<DateTime?>("Fecha")
                        .HasColumnType("datetime")
                        .HasColumnName("fecha");

                    b.Property<string>("PreguntaUsuario")
                        .HasColumnType("text")
                        .HasColumnName("pregunta_usuario");

                    b.Property<int?>("RespuestaId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("respuesta_id");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("TEXT")
                        .HasColumnName("usuario_id");

                    b.HasKey("LogId")
                        .HasName("PK__logs_ia__9E2397E08801C21A");

                    b.HasIndex("RespuestaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("logs_ia", (string)null);
                });

            modelBuilder.Entity("Pluxy3dBE.Entities.MediosPago", b =>
                {
                    b.Property<int>("MedioPagoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("medio_pago_id");

                    b.Property<bool?>("Activo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("activo");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("nombre");

                    b.HasKey("MedioPagoId")
                        .HasName("PK__medios_p__56065D0527EE448D");

                    b.ToTable("medios_pago", (string)null);
                });

            modelBuilder.Entity("Pluxy3dBE.Entities.MensajesTicket", b =>
                {
                    b.Property<int>("MensajeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("mensaje_id");

                    b.Property<string>("Contenido")
                        .HasColumnType("text")
                        .HasColumnName("contenido");

                    b.Property<DateTime?>("FechaEnvio")
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_envio");

                    b.Property<int?>("TicketId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ticket_id");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("TEXT")
                        .HasColumnName("usuario_id");

                    b.HasKey("MensajeId")
                        .HasName("PK__mensajes__6B304DCDEFFC63D8");

                    b.HasIndex("TicketId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("mensajes_ticket", (string)null);
                });

            modelBuilder.Entity("Pluxy3dBE.Entities.NewsletterSuscripcione", b =>
                {
                    b.Property<int>("SuscripcionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("suscripcion_id");

                    b.Property<bool?>("Activo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("activo");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<DateTime?>("FechaAlta")
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_alta");

                    b.HasKey("SuscripcionId")
                        .HasName("PK__newslett__855431D0987B0979");

                    b.ToTable("newsletter_suscripciones", (string)null);
                });

            modelBuilder.Entity("Pluxy3dBE.Entities.OpcionesComponente", b =>
                {
                    b.Property<int>("OpcionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("opcion_id");

                    b.Property<int?>("ComponenteId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("componente_id");

                    b.Property<string>("ImagenUrl")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("imagen_url");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("nombre");

                    b.Property<decimal?>("PrecioAdicional")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("precio_adicional");

                    b.HasKey("OpcionId")
                        .HasName("PK__opciones__FFA6A8F8F0655382");

                    b.HasIndex("ComponenteId");

                    b.ToTable("opciones_componentes", (string)null);
                });

            modelBuilder.Entity("Pluxy3dBE.Entities.Pago", b =>
                {
                    b.Property<int>("PagoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("pago_id");

                    b.Property<string>("Estado")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("FechaPago")
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_pago");

                    b.Property<int?>("MedioPagoId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("medio_pago_id");

                    b.Property<decimal?>("Monto")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("monto");

                    b.Property<int?>("VentaId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("venta_id");

                    b.HasKey("PagoId")
                        .HasName("PK__pagos__FFF0A58E3A93F693");

                    b.HasIndex("MedioPagoId");

                    b.HasIndex("VentaId");

                    b.ToTable("pagos", (string)null);
                });

            modelBuilder.Entity("Pluxy3dBE.Entities.Producto", b =>
                {
                    b.Property<int>("ProductoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("producto_id");

                    b.Property<int?>("CategoriaId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("categoria_id");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("descripcion");

                    b.Property<string>("Image")
                        .HasColumnType("TEXT")
                        .HasColumnName("image");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("nombre");

                    b.Property<decimal?>("PrecioBase")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("precio_base");

                    b.Property<int?>("Stock")
                        .HasColumnType("INTEGER")
                        .HasColumnName("stock");

                    b.Property<bool?>("Visible")
                        .HasColumnType("INTEGER")
                        .HasColumnName("visible");

                    b.HasKey("ProductoId")
                        .HasName("PK__producto__FB5CEEECEE4023FE");

                    b.HasIndex("CategoriaId");

                    b.ToTable("productos", (string)null);
                });

            modelBuilder.Entity("Pluxy3dBE.Entities.ResenasProducto", b =>
                {
                    b.Property<int>("ResenaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("resena_id");

                    b.Property<string>("Comentario")
                        .HasColumnType("text")
                        .HasColumnName("comentario");

                    b.Property<DateTime?>("Fecha")
                        .HasColumnType("datetime")
                        .HasColumnName("fecha");

                    b.Property<int?>("ProductoId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("producto_id");

                    b.Property<int?>("Puntaje")
                        .HasColumnType("INTEGER")
                        .HasColumnName("puntaje");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("TEXT")
                        .HasColumnName("usuario_id");

                    b.HasKey("ResenaId")
                        .HasName("PK__resenas___642724501C1F752B");

                    b.HasIndex("ProductoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("resenas_productos", (string)null);
                });

            modelBuilder.Entity("Pluxy3dBE.Entities.RespuestasIum", b =>
                {
                    b.Property<int>("RespuestaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("respuesta_id");

                    b.Property<string>("PreguntaClave")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("pregunta_clave");

                    b.Property<string>("RespuestaTexto")
                        .HasColumnType("text")
                        .HasColumnName("respuesta_texto");

                    b.HasKey("RespuestaId")
                        .HasName("PK__respuest__5D54E93D4E4C9077");

                    b.ToTable("respuestas_ia", (string)null);
                });

            modelBuilder.Entity("Pluxy3dBE.Entities.Role", b =>
                {
                    b.Property<int>("RolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("rol_id");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("nombre");

                    b.HasKey("RolId")
                        .HasName("PK__roles__CF32E443E00AD312");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("Pluxy3dBE.Entities.SimpleCartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("producto_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER")
                        .HasColumnName("cantidad");

                    b.HasKey("Id");

                    b.ToTable("simple_cart_items", (string)null);
                });

            modelBuilder.Entity("Pluxy3dBE.Entities.TicketsSoporte", b =>
                {
                    b.Property<int>("TicketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ticket_id");

                    b.Property<string>("Asunto")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("asunto");

                    b.Property<string>("Estado")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_creacion");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("TEXT")
                        .HasColumnName("usuario_id");

                    b.HasKey("TicketId")
                        .HasName("PK__tickets___D596F96BFDB74479");

                    b.HasIndex("UsuarioId");

                    b.ToTable("tickets_soporte", (string)null);
                });

            modelBuilder.Entity("Pluxy3dBE.Entities.Usuario", b =>
                {
                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("TEXT")
                        .HasColumnName("usuario_id");

                    b.Property<bool?>("Activo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("activo");

                    b.Property<string>("Apellido")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("apellido");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<DateTime?>("FechaRegistro")
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_registro");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("nombre");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("password_hash");

                    b.HasKey("UsuarioId")
                        .HasName("PK__usuarios__2ED7D2AFB0688E30");

                    b.HasIndex(new[] { "Email" }, "UQ__usuarios__AB6E6164050A4AD0")
                        .IsUnique();

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("Pluxy3dBE.Entities.Venta", b =>
                {
                    b.Property<int>("VentaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("venta_id");

                    b.Property<int?>("DireccionEnvioId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("direccion_envio_id");

                    b.Property<int?>("EstadoId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("estado_id");

                    b.Property<DateTime?>("FechaVenta")
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_venta");

                    b.Property<decimal?>("Total")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("total");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("TEXT")
                        .HasColumnName("usuario_id");

                    b.HasKey("VentaId")
                        .HasName("PK__ventas__B135080906DF1020");

                    b.HasIndex("DireccionEnvioId");

                    b.HasIndex("EstadoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("ventas", (string)null);
                });

            modelBuilder.Entity("UsuarioRole", b =>
                {
                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("TEXT")
                        .HasColumnName("usuario_id");

                    b.Property<int>("RolId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("rol_id");

                    b.HasKey("UsuarioId", "RolId")
                        .HasName("PK__usuario___0224FCEB9141F2BA");

                    b.HasIndex("RolId");

                    b.ToTable("usuario_roles", (string)null);
                });

            modelBuilder.Entity("Pluxy3dBE.Entities.Carrito", b =>
                {
                    b.HasOne("Pluxy3dBE.Entities.Usuario", "Usuario")
                        .WithMany("Carritos")
                        .HasForeignKey("UsuarioId")
                        .HasConstraintName("FK__carritos__usuari__5070F446");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Pluxy3dBE.Entities.CarritoItem", b =>
                {
                    b.HasOne("Pluxy3dBE.Entities.Carrito", "Carrito")
                        .WithMany("CarritoItems")
                        .HasForeignKey("CarritoId")
                        .HasConstraintName("FK__carrito_i__carri__534D60F1");

                    b.HasOne("Pluxy3dBE.Entities.ImpresorasPersonalizada", "Impresora")
                        .WithMany("CarritoItems")
                        .HasForeignKey("ImpresoraId")
                        .HasConstraintName("FK__carrito_i__impre__5441852A");

                    b.Navigation("Carrito");

                    b.Navigation("Impresora");
                });

            modelBuilder.Entity("Pluxy3dBE.Entities.DetalleVentum", b =>
                {
                    b.HasOne("Pluxy3dBE.Entities.ImpresorasPersonalizada", "Impresora")
                        .WithMany("DetalleVenta")
                        .HasForeignKey("ImpresoraId")
                        .HasConstraintName("FK__detalle_v__impre__6383C8BA");

                    b.HasOne("Pluxy3dBE.Entities.Venta", "Venta")
                        .WithMany("DetalleVenta")
                        .HasForeignKey("VentaId")
                        .HasConstraintName("FK__detalle_v__venta__628FA481");

                    b.Navigation("Impresora");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("Pluxy3dBE.Entities.DireccionesUsuario", b =>
                {
                    b.HasOne("Pluxy3dBE.Entities.Usuario", "Usuario")
                        .WithMany("DireccionesUsuarios")
                        .HasForeignKey("UsuarioId")
                        .HasConstraintName("FK__direccion__usuar__403A8C7D");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Pluxy3dBE.Entities.FavoritosUsuario", b =>
                {
                    b.HasOne("Pluxy3dBE.Entities.Producto", "Producto")
                        .WithMany("FavoritosUsuarios")
                        .HasForeignKey("ProductoId")
                        .HasConstraintName("FK__favoritos__produ__02084FDA");

                    b.HasOne("Pluxy3dBE.Entities.Usuario", "Usuario")
                        .WithMany("FavoritosUsuarios")
                        .HasForeignKey("UsuarioId")
                        .HasConstraintName("FK__favoritos__usuar__01142BA1");

                    b.Navigation("Producto");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Pluxy3dBE.Entities.HistorialNavegacion", b =>
                {
                    b.HasOne("Pluxy3dBE.Entities.Usuario", "Usuario")
                        .WithMany("HistorialNavegacions")
                        .HasForeignKey("UsuarioId")
                        .HasConstraintName("FK__historial__usuar__7E37BEF6");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Pluxy3dBE.Entities.ImpresorasPersonalizada", b =>
                {
                    b.HasOne("Pluxy3dBE.Entities.Producto", "Producto")
                        .WithMany("ImpresorasPersonalizada")
                        .HasForeignKey("ProductoId")
                        .HasConstraintName("FK__impresora__produ__4D94879B");

                    b.HasOne("Pluxy3dBE.Entities.Usuario", "Usuario")
                        .WithMany("ImpresorasPersonalizada")
                        .HasForeignKey("UsuarioId")
                        .HasConstraintName("FK__impresora__usuar__4CA06362");

                    b.Navigation("Producto");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Pluxy3dBE.Entities.LogsIum", b =>
                {
                    b.HasOne("Pluxy3dBE.Entities.RespuestasIum", "Respuesta")
                        .WithMany("LogsIa")
                        .HasForeignKey("RespuestaId")
                        .HasConstraintName("FK__logs_ia__respues__75A278F5");

                    b.HasOne("Pluxy3dBE.Entities.Usuario", "Usuario")
                        .WithMany("LogsIa")
                        .HasForeignKey("UsuarioId")
                        .HasConstraintName("FK__logs_ia__usuario__74AE54BC");

                    b.Navigation("Respuesta");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Pluxy3dBE.Entities.MensajesTicket", b =>
                {
                    b.HasOne("Pluxy3dBE.Entities.TicketsSoporte", "Ticket")
                        .WithMany("MensajesTickets")
                        .HasForeignKey("TicketId")
                        .HasConstraintName("FK__mensajes___ticke__6EF57B66");

                    b.HasOne("Pluxy3dBE.Entities.Usuario", "Usuario")
                        .WithMany("MensajesTickets")
                        .HasForeignKey("UsuarioId")
                        .HasConstraintName("FK__mensajes___usuar__6FE99F9F");

                    b.Navigation("Ticket");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Pluxy3dBE.Entities.OpcionesComponente", b =>
                {
                    b.HasOne("Pluxy3dBE.Entities.ComponentesPersonalizable", "Componente")
                        .WithMany("OpcionesComponentes")
                        .HasForeignKey("ComponenteId")
                        .HasConstraintName("FK__opciones___compo__49C3F6B7");

                    b.Navigation("Componente");
                });

            modelBuilder.Entity("Pluxy3dBE.Entities.Pago", b =>
                {
                    b.HasOne("Pluxy3dBE.Entities.MediosPago", "MedioPago")
                        .WithMany("Pagos")
                        .HasForeignKey("MedioPagoId")
                        .HasConstraintName("FK__pagos__medio_pag__693CA210");

                    b.HasOne("Pluxy3dBE.Entities.Venta", "Venta")
                        .WithMany("Pagos")
                        .HasForeignKey("VentaId")
                        .HasConstraintName("FK__pagos__venta_id__68487DD7");

                    b.Navigation("MedioPago");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("Pluxy3dBE.Entities.Producto", b =>
                {
                    b.HasOne("Pluxy3dBE.Entities.CategoriasProducto", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("CategoriaId")
                        .HasConstraintName("FK__productos__categ__44FF419A");

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("Pluxy3dBE.Entities.ResenasProducto", b =>
                {
                    b.HasOne("Pluxy3dBE.Entities.Producto", "Producto")
                        .WithMany("ResenasProductos")
                        .HasForeignKey("ProductoId")
                        .HasConstraintName("FK__resenas_p__produ__797309D9");

                    b.HasOne("Pluxy3dBE.Entities.Usuario", "Usuario")
                        .WithMany("ResenasProductos")
                        .HasForeignKey("UsuarioId")
                        .HasConstraintName("FK__resenas_p__usuar__787EE5A0");

                    b.Navigation("Producto");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Pluxy3dBE.Entities.TicketsSoporte", b =>
                {
                    b.HasOne("Pluxy3dBE.Entities.Usuario", "Usuario")
                        .WithMany("TicketsSoportes")
                        .HasForeignKey("UsuarioId")
                        .HasConstraintName("FK__tickets_s__usuar__6C190EBB");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Pluxy3dBE.Entities.Venta", b =>
                {
                    b.HasOne("Pluxy3dBE.Entities.DireccionesUsuario", "DireccionEnvio")
                        .WithMany("Venta")
                        .HasForeignKey("DireccionEnvioId")
                        .HasConstraintName("FK__ventas__direccio__5FB337D6");

                    b.HasOne("Pluxy3dBE.Entities.EstadosVentum", "Estado")
                        .WithMany("Venta")
                        .HasForeignKey("EstadoId")
                        .HasConstraintName("FK__ventas__estado_i__5EBF139D");

                    b.HasOne("Pluxy3dBE.Entities.Usuario", "Usuario")
                        .WithMany("Venta")
                        .HasForeignKey("UsuarioId")
                        .HasConstraintName("FK__ventas__usuario___5DCAEF64");

                    b.Navigation("DireccionEnvio");

                    b.Navigation("Estado");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("UsuarioRole", b =>
                {
                    b.HasOne("Pluxy3dBE.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RolId")
                        .IsRequired()
                        .HasConstraintName("FK__usuario_r__rol_i__3D5E1FD2");

                    b.HasOne("Pluxy3dBE.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .IsRequired()
                        .HasConstraintName("FK__usuario_r__usuar__3C69FB99");
                });

            modelBuilder.Entity("Pluxy3dBE.Entities.Carrito", b =>
                {
                    b.Navigation("CarritoItems");
                });

            modelBuilder.Entity("Pluxy3dBE.Entities.CategoriasProducto", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("Pluxy3dBE.Entities.ComponentesPersonalizable", b =>
                {
                    b.Navigation("OpcionesComponentes");
                });

            modelBuilder.Entity("Pluxy3dBE.Entities.DireccionesUsuario", b =>
                {
                    b.Navigation("Venta");
                });

            modelBuilder.Entity("Pluxy3dBE.Entities.EstadosVentum", b =>
                {
                    b.Navigation("Venta");
                });

            modelBuilder.Entity("Pluxy3dBE.Entities.ImpresorasPersonalizada", b =>
                {
                    b.Navigation("CarritoItems");

                    b.Navigation("DetalleVenta");
                });

            modelBuilder.Entity("Pluxy3dBE.Entities.MediosPago", b =>
                {
                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("Pluxy3dBE.Entities.Producto", b =>
                {
                    b.Navigation("FavoritosUsuarios");

                    b.Navigation("ImpresorasPersonalizada");

                    b.Navigation("ResenasProductos");
                });

            modelBuilder.Entity("Pluxy3dBE.Entities.RespuestasIum", b =>
                {
                    b.Navigation("LogsIa");
                });

            modelBuilder.Entity("Pluxy3dBE.Entities.TicketsSoporte", b =>
                {
                    b.Navigation("MensajesTickets");
                });

            modelBuilder.Entity("Pluxy3dBE.Entities.Usuario", b =>
                {
                    b.Navigation("Carritos");

                    b.Navigation("DireccionesUsuarios");

                    b.Navigation("FavoritosUsuarios");

                    b.Navigation("HistorialNavegacions");

                    b.Navigation("ImpresorasPersonalizada");

                    b.Navigation("LogsIa");

                    b.Navigation("MensajesTickets");

                    b.Navigation("ResenasProductos");

                    b.Navigation("TicketsSoportes");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("Pluxy3dBE.Entities.Venta", b =>
                {
                    b.Navigation("DetalleVenta");

                    b.Navigation("Pagos");
                });
#pragma warning restore 612, 618
        }
    }
}
