name: Azure Static Web Apps CI/CD

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'pluxy3d/**'
      - '.github/workflows/azure-static-web-apps-black-rock-07326140f.yml'
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
    paths:
      - 'pluxy3d/**'

# Prevent concurrent deployments
concurrency:
  group: frontend-deployment
  cancel-in-progress: false

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "./pluxy3d"
          app_build_command: "npm install --legacy-peer-deps && npm run build"
        env:
          NEXT_PUBLIC_API_URL: "https://pluxy3d-api-prod-d9h2f3gpf8cmcqd9.eastus2-01.azurewebsites.net/api"

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "close"
          app_location: "./pluxy3d"
